version: '3'

services:
  elevator-system:
    build: ./ElevatorSystem
    hostname: elevator-system
    volumes:
      - ./ElevatorSystem:/tmp
    ports:
      - 8001:8001
    networks:
      app_net:
        ipv4_address: 172.16.200.5

  scheduler:
    build: ./Scheduler
    hostname: scheduler
    volumes:
      - ./Scheduler:/tmp
    ports:
      - 8080:8080
    networks:
      app_net:
        ipv4_address: 172.16.200.4

  floor-system:
    build: ./FloorSystem
    hostname: floor-system
    volumes:
      - ./FloorSystem:/tmp
    ports:
      - 8003:8003
    networks:
      app_net:
        ipv4_address: 172.16.200.3

  simulator:
    build: ./Simulator
    hostname: simulator
    volumes:
      - ./Simulator:/tmp
    ports:
      - 8002:8002
    networks:
      app_net:
        ipv4_address: 172.16.200.2

  rabbitmq:
    image: rabbitmq
    hostname: rabbit
    ports:
      - 5672:5672
    networks:
      app_net:
        ipv4_address: 172.16.200.6

  analyzer:
    build: ./Analyzer
    hostname: analyzer
    volumes:
      - ./Analyzer:/tmp
    networks:
      app_net:
        ipv4_address: 172.16.200.7

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/16
