@startuml

skinparam linetype polyline

component GUI

  package "FloorSystem"{
  component FloorSystem as fl
  }

  package "ElevatorSystem" {
  component ElevatorSystem as el
  }

package "Simulator"{
  component Simulator as sim
}

package "Scheduler"{
component SchedulerSystem as sched
}


package "RabbitMQ"{
  queue "ElevatorQueue"
  queue "FloorQueue"
  queue "GUIQueue"
  queue "SimQueue"
  queue "SchedulerQueue"
}

sim -up-> ElevatorQueue: pub
sim -up-> FloorQueue: pub
sim <-up- SimQueue: sub

el --> SchedulerQueue: pub
el --> GUIQueue: pub
el <-- ElevatorQueue: sub

fl --> SchedulerQueue: pub
fl --> SimQueue: pub
fl --> GUIQueue : pub
fl <-- FloorQueue : sub

sched -up-> FloorQueue: pub
sched -up-> ElevatorQueue: pub
sched <-up- SchedulerQueue: sub

GUIQueue --> GUI : sub
FloorQueue <-- GUI : pub
ElevatorQueue <-- GUI: pub



@enduml
